### PR TITLE
example

### PR DESCRIPTION
**Pull request by Idodoqdo**
hello, I decided to try your library and faced with the fact that the example does not work. Can you suggest: is your library worth using?

### CODE REVIEW

**Comment by coder-gogo** [comment]
> hello, I decided to try your library and faced with the fact that the example does not work. Can you suggest: is your library worth using?

yes its working perfectly could you please give me some hint where you faced issue.
so i can help you

**Comment by Idodoqdo** [comment]
code out of your example:
Unhandled exception:
Null check operator used on a null value
#0      MessageSet._messageToBytes (package:kafkabr/src/protocol/messages.dart:102:33)
#1      MessageSet.toBytes.<anonymous closure> (package:kafkabr/src/protocol/messages.dart:89:25)
#2      ListMapView.forEach (dart:_internal/list.dart:242:8)
#3      MessageSet.toBytes (package:kafkabr/src/protocol/messages.dart:88:15)
#4      ProduceRequest.toBytes.<anonymous closure>.<anonymous closure> (package:kafkabr/src/protocol/produce_api.dart:50:38)
#5      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:625:13)
#6      ProduceRequest.toBytes.<anonymous closure> (package:kafkabr/src/protocol/produce_api.dart:48:18)
#7      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:625:13)
#8      ProduceRequest.toBytes (package:kafkabr/src/protocol/produce_api.dart:45:17)
#9      KafkaSession._send.<anonymous closure> (package:kafkabr/src/session.dart:165:26)
<asynchronous suspension>

I would be very grateful if you could write a simple working example
And why do you write 'new'?
Thx

**Comment by Idodoqdo** [comment]
The problem is here:
` List<int> _messageToBytes(Message message) {
    var builder = KafkaBytesBuilder();
    builder.addInt8(0); // magicByte
    builder.addInt8(message.attributes!.toInt());
    builder.addBytes(message.key!);
    builder.addBytes(message.value);
`

**Comment by coder-gogo** [comment]
i'm sorry but master branch has some issue so for work around you can use this branch and it's example 
v.1.0.2 which i just have pushed. and tell me that it's working for you or not.

and please tell me if you found any issue. so i can help you. thx

**Comment by Idodoqdo** [comment]
Okay, I'll deal with it next business day. In touch?

**Comment by coder-gogo** [comment]
> Okay, I'll deal with it next business day. In touch?

you can contact me on my skype

live:.cid.38ab440992f705b4

**Pull request merged**
